### PR TITLE
Disable node execution for remote content

### PR DESCRIPTION
**Pull request by JoeRoddy**
Fix security warning.

More info: 
https://stackoverflow.com/questions/48854265/why-do-i-see-an-electron-security-warning-after-updating-my-electron-project-t

### CODE REVIEW

**Comment by alexvcasillas** [comment]
I'm not sure I can accept this PR 🤔 
Where's the preload.js file you're referencing?
Just setting the `nodeIntegration: false` would solve the warning that appears at development?

**Comment by JoeRoddy** [comment]
Yep, I pasted too quickly without looking!  That prop could be used later if you need to execute node from web apis or something.

**Comment by alexvcasillas** [comment]
Can you post a screenshot of the current running application with this change? I'm not on a computer so I can't test this right now :)

**Comment by JoeRoddy** [comment]
Hah, it's not something that needs to be merged this instant.  I can also only test on linux atm.

before:
reactron - development_004

after:
reactron - development_005

**Comment by alexvcasillas** [comment]
Awesome! I'm gonna merge it : )

Thanks for the PR, mate! 😉

**Review by alexvcasillas — APPROVED** [review]

**Pull request merged**
